--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/artsvn/VanishV2
build-by-default: true
branches:
- PM4
projects:
  VanishV2:
    path: ""
    libs:
      - src: muqsit/InvMenu/InvMenu
        version: ^4.4.1
        branch: "4.0"
...
